### ISSUE TITLE
consider different locales

### ISSUE THREAD

**Issue by ctf0** [thepinecode/i18n#1]
according to https://pineco.de/using-laravels-localization-js/ we get the default locale and cache it, but what happens when u change the locale ?

the lib can take care of this by switching the translation according to the current app locale which can be acquired by using props on the vue comp init and send it as an option to the class constructor.

then we check if the locale is found in the translations keys locales and either fallback to the default or display empty string, which could be another option sent to the class constructor

**Comment by iamgergo** [comment]
@ctf0 Thank you for the idea! 

Since we need the current language's files, we can solve it only at the back-end side.
You are right, we need to change the default config to the current locale.

So that means we need to change this:
``config('app.locale')``
to this 
``app()->getLocale()``

That means we don't need to pass any locale argument to the translator constructor.
If I need the current locale anywhere in my JS, I often do this:

``<html lang="{{ app()->getLocale() }}">``
and then
``let lang = document.documentElement.lang``

Also, that might would be a good solution, instead of using cache here, we could use view composers. Then we could react immediately to the local changes.

What do you think?

**Comment by ctf0** [comment]
i was thinking more of fetching all the locales and save it to the localeStorage like

```js
'required': {
    en: 'english text',
    fr: 'french text'
}
```

this way you only prepare the trans once, instead of going through the whole thing each time the user change the locale.

also whether using `config('app.locale')` or `app()->getLocale()` its the same as `getLocale()` basically return `config('app.locale')`

still, if you prefer to keep the lib as light as possible, we can maybe do all on the backend and display the result as a blade directive like https://github.com/tightenco/ziggy , this way you dont need to use cache as blade take care of this & it will auto-invalidate when new trans gets added.

**Comment by iamgergo** [comment]
@ctf0 Hmm, this ``getLocale()`` thing is new for me! Thank you!

I think I would keep the JS part like this, this is maintainable for us this way.

But I love the idea about the blade directive!
I think I extract the back-end part to a package with the blade directive part.

I link the package here soon!

Thank you for your ideas! :)

**Comment by iamgergo** [comment]
So we created a package, you can find the docs in the readme!
I close this issue, if you think, be brave to open a new issue!

Thank you for the idea!

**Comment by ctf0** [comment]
so i believe it would make more sense if importing the `i18n` already comes bundled with the translations.

as atm we need to do 3 steps
- add `window.translations = @translations;` to view
- import I18n
- init the lib `let translator = new I18n(window.translations);`
