### ISSUE TITLE
Local package commands not found

### ISSUE THREAD

**Issue by Futskito** [thepinecode/i18n#23]
It's a rare bug that I found today...

If you have any local package registered in your app, and you have i18n installed, laravel seems to be unable to register package commands with the typical code in the package Service Provider:

if($this->app->runningInConsole()){
    $this->commands([
        MyCommandClass:class,
    ]);
}

**Comment by rafatga** [comment]
Hi Adam,
My colleague @Futskito and I started using your laravel package to handle the vue translations system. Unfortunately today we ran into an error that made us lose, quite some time and we decided to migrate to another library.

Even though we already moved to another library I will try to explain the error so you can fix it for your current and future users.

In all our projects we divide our code in domains, so we create Modules using composer and laravel.
[https://github.com/rafatga/thepinecode-i18n-issue](https://github.com/rafatga/thepinecode-i18n-issue)

**Issue description**
If your project has modules and you register your commands in you module provider you will see that as soon as you install the library (thepinecode /i18n) your commands will be unregistered and you will get the error ( There are no commands defined in the "resourcing" namespace. )

<img width="661" alt="Screen Shot 2020-07-03 at 9 46 16 PM" src="https://user-images.githubusercontent.com/3813277/86495418-92cfb600-bd79-11ea-9c0a-58f379293bb7.png">


[https://github.com/rafatga/thepinecode-i18n-issue/blob/master/Modules/Admin/Providers/AdminServiceProvider.php](https://github.com/rafatga/thepinecode-i18n-issue/blob/master/Modules/Admin/Providers/AdminServiceProvider.php)
<img width="345" alt="Screen Shot 2020-07-03 at 10 06 41 PM" src="https://user-images.githubusercontent.com/3813277/86495412-89464e00-bd79-11ea-824b-8f2d6e452e10.png">

**Before installing (thepinecode /i18n)**
As you can see when you write the command (php artisan list) it appears the command registered (admin:install) & (frontend:install)
<img width="1036" alt="Screen Shot 2020-07-03 at 9 44 31 PM" src="https://user-images.githubusercontent.com/3813277/86495536-1a1d2980-bd7a-11ea-81c2-d99398ecd7cd.png">

**After the installation of (thepinecode /i18n)**
After the installation of the library you will see that the commands does not appear registered anymore.
<img width="1035" alt="Screen Shot 2020-07-03 at 9 47 29 PM" src="https://user-images.githubusercontent.com/3813277/86495670-9b74bc00-bd7a-11ea-8060-2371db6fdea3.png">


**Bug**
 The reason why the commands get unregistered is because the library (thepinecode /i18n) executes the command (view:clear) in the function boot of the provider.

<img width="500" alt="Screen Shot 2020-07-03 at 10 16 38 PM" src="https://user-images.githubusercontent.com/3813277/86495810-25bd2000-bd7b-11ea-8f76-a7387b4a9ba6.png">

**Comment by iamgergo** [comment]
@rafatga @Futskito Hi,

Thanks for reporting the issue! I'll revert the view clear command.
It can make local development a bit slower, but there are some interesting conflicts.

Thanks again!

**Comment by iamgergo** [comment]
https://github.com/thepinecode/i18n/pull/18 is reverted now.
